import Footer from '@/components/layout/footer/Footer'
import type { Metadata } from 'next'
import dynamic from 'next/dynamic'
import { Onest } from 'next/font/google'
import './globals.scss'
import Providers from './providers'

const onest = Onest({ subsets: ['latin'], display: 'swap', adjustFontFallback: false })

export const metadata: Metadata = {
    title: 'Cariere Novalines',
    description: 'Generated by create next app',
    icons: {
        icon: ['/favicons/favicon.ico', '/favicons/favicon-16x16.png', '/favicons/favicon-32x32.png'],
        apple: ['/favicons/apple-touch-icon.png', '/favicons/safari-pinned-tab.svg'],

    }
}

const Header = dynamic(() => import('@/components/layout/header/Header'), { ssr: false })

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={onest.className}>
                <Providers>
                    <Header />
                    <main>{children}</main>

                    <Footer />
                </Providers>
            </body>
        </html>
    )
}
