import Footer from '@/components/layout/footer/Footer'
import type { Metadata } from 'next'
import dynamic from 'next/dynamic'
import { Onest } from 'next/font/google'
import './globals.scss'
import Providers from './providers'

const onest = Onest({ subsets: ['latin'], display: 'swap', adjustFontFallback: false })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const Header = dynamic(() => import('@/components/layout/header/Header'), { ssr: false })

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={onest.className}>
                <Providers>
                    <Header />
                    <main>{children}</main>

                    <Footer />
                </Providers>
            </body>
        </html>
    )
}
