import type { Metadata } from "next"
import dynamic from 'next/dynamic'
import { Inter } from "next/font/google"
import "./globals.scss"
import Providers from './providers'

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const DynamicHeader = dynamic(() => import('@/components/layout/header/Header'), { ssr: false })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <DynamicHeader />
          {children}
        </Providers>
      </body>
    </html>
  )
}
